### ISSUE TITLE
Download results button occasionally disabled

### ISSUE THREAD

**Issue by lukavdplas** [UUDigitalHumanitieslab/I-analyzer#1029]
If you go to the visualisation tab and update the query or filters, the download button will be disabled.

It used to be that updating the query would always take you to the results tab as well, so this is a recent phenomenon. This happens because the frontend has not requested results, and thus the `resultCount` is 0.

This is a minor issue, but it's not great UI to disable a button when there is no reason why it cannot be executed. And while users can still download by switching to the results tab, they have no way of knowing that.

Could be resolved by:
- Making a search request (with `size = 0` for speed) to probe the total number of results 
- Implementing the layout change I propose in #674, to move the download button into the results tab.

**Comment by JeltevanBoheemen** [comment]
Suggested to implement https://github.com/UUDigitalHumanitieslab/I-analyzer/issues/1310 instead.
