### ISSUE TITLE
Times corpus filter not working

### ISSUE THREAD

**Issue by Meesch** [UUDigitalHumanitieslab/I-analyzer#1044]
The filter 'On front page' True/False is not working properly anymore. When selecting the filter, i.e. set it to True, it shows 0 entries.

<img width="1086" alt="Screenshot 2023-01-25 at 10 39 42" src="https://user-images.githubusercontent.com/31687030/214529502-4a51e7bd-de0a-4e5e-af01-9c54576dab90.png">

**Comment by JeltevanBoheemen** [comment]
Disabled the filter for now
