### ISSUE TITLE
Times scans script is outdated

### ISSUE THREAD

**Issue by lukavdplas** [UUDigitalHumanitieslab/I-analyzer#1055]
The `times_scans.py` script was last updated in 2018 so it is broken in several places. Amongst other things, it can't retrieve corpus definitions, gets the 'default' elasticsearch cluster regardless of whether the times index is on that cluster, and does not use the proper setup for the elasticsearch python client.

It looks like the script is intended to add image data to the elasticsearch index. Since the index is already present, we probably won't have reason to run this script again the future.

It's not really worth it to fix up the script, I'm just making the issue to note that this problem exists.

**Comment by BeritJanssen** [comment]
I think #1368 took care of this.
