### ISSUE TITLE
Include elasticsearch in github test action

### ISSUE THREAD

**Issue by lukavdplas** [UUDigitalHumanitieslab/I-analyzer#1186]
Our [test action](https://github.com/UUDigitalHumanitieslab/I-analyzer/blob/develop/.github/workflows/test.yml) does not run elasticsearch, but perhaps this can be added now that @BeritJanssen finished the docker configuration?

**Comment by BeritJanssen** [comment]
I'd hoped that tests depending on Elasticsearch would now be run, but I still see ~80 tests skipped.
