### ISSUE TITLE
x-axis of troonredes / dutch annual reports word models

### ISSUE THREAD

**Issue by lukavdplas** [UUDigitalHumanitieslab/I-analyzer#1188]
Screenshot from the troonredes below. This doesn´t look right:

![image](https://github.com/UUDigitalHumanitieslab/I-analyzer/assets/43678097/1a33470f-6a0e-4382-af53-38dddfac9888)

I think the issue here is that the complete model is included as if it is one of the binned models, and it just needs to be removed from the server.

**Comment by BeritJanssen** [comment]
Done!
