### ISSUE TITLE
Reinstate e2e testing

### ISSUE THREAD

**Issue by JeltevanBoheemen** [UUDigitalHumanitieslab/I-analyzer#1218]
Removed Protractor due to [deprecation](https://github.com/angular/protractor/issues/5502).
Decide on a new e2e framework and implement it.

**Comment by jgonggrijp** [comment]
Wait, what's wrong with using the `functional-tests` subproject? Isn't pytest+webdriver way nicer to use than something like protractor?

**Comment by JeltevanBoheemen** [comment]
Good point!
