### ISSUE TITLE
Date filter from route bug 

### ISSUE THREAD

**Issue by Meesch** [UUDigitalHumanitieslab/I-analyzer#1219]
When you try to navigate to a query with a date filter in the route, it will give you a `ExpressionChangedAfterItHasBeenCheckedError` and reset the date filter to the defaults. The error is only shown explicitly in the dev environment because the prod environment suppresses the error message, but the bug exists in both. I will try and tackle this after lunch.

**Comment by BeritJanssen** [comment]
I also found that it's not possible to change the filters from the route anymore.

**Comment by lukavdplas** [comment]
for the date filter, yes, that is the same issue. did you observe this for other filters?

**Comment by BeritJanssen** [comment]
No, this seems to be only a problem for the date filter, indeed.
