### ISSUE TITLE
Email sender "example.com"

### ISSUE THREAD

**Issue by BeritJanssen** [UUDigitalHumanitieslab/I-analyzer#1220]
@JeltevanBoheemen is this caused by missing settings in People & Parliament?
![Screenshot 2023-08-03 at 17 00 43](https://github.com/UUDigitalHumanitieslab/I-analyzer/assets/11174072/87a17d83-4ee5-4908-9fe2-3cb4b436e462)

**Comment by JeltevanBoheemen** [comment]
Yes. You need to set some value in `settings.py` and then run a migration again. I'll look them up for you tomorrow!

**Comment by JeltevanBoheemen** [comment]
I see the settings are correct in deployment. You'll need to run (on the server):
```
yarn django migrate users 0002 --settings settings --pythonpath /hum/web/<servername>/private
yarn django migrate users --settings settings --pythonpath /hum/web/<servername>/private
```
This will first undo migration `users 0003`, which handles setting `site.name` and `site.domain` and then rerun it. Alternatively you can edit the `Site` object (there should only be one) in the Django admin interface:
![image](https://github.com/UUDigitalHumanitieslab/I-analyzer/assets/4539142/91a75448-5e7a-415b-98a0-e4cc42883456)

It's a bit of a hassle, but it's the most consequent way to set the host in emails, which is needed for generating verification links.
