### ISSUE TITLE
Corpora / role don't seem set correctly after logging in with newly created user

### ISSUE THREAD

**Issue by BeritJanssen** [UUDigitalHumanitieslab/I-analyzer#1221]
I created a new user on the People & Parliament test server, but that user doesn't seem to have access to any corpora, even though all parliament corpora should be available for the "basic" group, and the new user is part of the "basic" group.

**Comment by lukavdplas** [comment]
can you still access the corpora as a superuser?

**Comment by BeritJanssen** [comment]
Everything can be accessed as superuser. The user rights are perhaps off with People & Parliament, as the groups were called something else ("core" vs. "parliaments" or something in that vein) on those servers. Can be fixed via the admin interface for the time being: we probably don't need to add new users at this point, and existing users haven't reported any problems.
