### ISSUE TITLE
Testing with `--loop-on-fail` loops (even when not failing)

### ISSUE THREAD

**Issue by JeltevanBoheemen** [UUDigitalHumanitieslab/I-analyzer#1225]
The tests keep on repeating themselves.  Probable cause is some files triggering live-reload unjustly. See [pytest-xdist](https://pytest-xdist.readthedocs.io/en/stable/#) for the functionality. Note `--loop-on-fail` says "DEPRECATED".

**Comment by JeltevanBoheemen** [comment]
Closing this. As mentioned `looponfail` is deprecated. I considered removing`pytest-xdist` as a whole, but it turns out `pytest -n auto` works flawlessly and is a considerable speedup.

**Comment by jgonggrijp** [comment]
Relevant: https://github.com/pytest-dev/pytest-xdist/issues/826
