### ISSUE TITLE
Use `range` option for date picker instead of two pickers?

### ISSUE THREAD

**Issue by BeritJanssen** [UUDigitalHumanitieslab/I-analyzer#1240]
Right now, we have two input fields and associated calendars to pick a range of dates, while PrimeNG currently also offers a `[range]` option to be set, meaning we have *one* input field and *one* calendar to manipulate. Perhaps this is worth investigating?

**Comment by lukavdplas** [comment]
I'm not sure I agree this would be preferable. Range pickers make sense when you would always be picking dates that are close together (e.g. for a hotel reservation). If you pick two ranges that are not close together (or co-dependent), the single picker can be annoying. Try using the primeNG picker to select 1900-2000 and then change it to 1910-2000, for an example.

**Comment by BeritJanssen** [comment]
Okay, let's close this for now. Seeing as the current widgets aren't ideal (and often, at least in Chrome, overlay the input field so dates cannot be typed), I will make a new issue.
