### ISSUE TITLE
Permitted Index Names

### ISSUE THREAD

**Issue by Meesch** [UUDigitalHumanitieslab/I-analyzer#1244]
Specifically for @BeritJanssen: 
 - We need some precise documentation on the new rules surrounding the index names
 - In load_corpus.py, in the `load_corpus` method, line 40+, the documentation says that "assume the class name of the endpoint is the same as the corpus name", which should probably be changed?

When this is fixed I can continue with the test indexing of the KB data!

**Comment by BeritJanssen** [comment]
This was actually already fixed - the docstring was just misleading here.
