### ISSUE TITLE
European Parliament

### ISSUE THREAD

**Issue by BeritJanssen** [UUDigitalHumanitieslab/I-analyzer#1250]
All speeches of the European Parliament are archived, translated to English. Potentially, this will be added as a corpus in 2024.

**Comment by BeritJanssen** [comment]
There is a scraped version, converted to linked data, available from https://ssh.datastations.nl/dataset.xhtml?persistentId=doi:10.17026/dans-x62-ew3m. The suggestion was to start with this dataset, and then use the *English* version. The corpus information should include a warning that the speeches can be in a different original language.

Metadata is limited: the vocabulary is rich, but all speeches seem to have `lpv:unclassifiedMetadata` as a predicate.

Data that can be extracted:
- date
- order in debate
- not systematic: original language  -> some objects of `lpv:translatedText` start with a language isocode in brackets, e.g., "(IT)"
- not systematic: speaker -> object of `lpv:unclassifiedMetadata` predicates - though this contains data such as `President`, and may either have full names or just the surname
- not systematic: speaker party -> object of `lpv:unclassifiedMetadata` contains party indication in brackets (e.g., "(PSE)"

**Comment by BeritJanssen** [comment]
@jgonggrijp this was the corpus I told you about. As we need to read turtle to process this corpus, I'm currently thinking to integrate rdflib in I-Analyzer and make RDFExtractors based on it. Or @lukavdplas is this something to rather start in the new repo?

**Comment by lukavdplas** [comment]
If you want to merge things within the next month or so, then you should do it in I-analyzer. Otherwise, it will save time to build it in the ianalyzer-reader package from the start.
