### ISSUE TITLE
Students no longer have access to paid corpora

### ISSUE THREAD

**Issue by Meesch** [UUDigitalHumanitieslab/I-analyzer#1277]
The two students in the I-A workshop did not have access to the non-public corpora, even though they should have access. Potentially something that went wrong with the migration?

**Comment by lukavdplas** [comment]
From what I can tell, SAML users used to added to a `'uu'` group:

https://github.com/UUDigitalHumanitieslab/I-analyzer/blob/84004edd4adba215bc00b2e895e6f3a89cb81222/backend/saml/views.py#L104-L122

That group still exists, but it looks like newly registered users don't get added to the group:

https://github.com/UUDigitalHumanitieslab/I-analyzer/blob/bf7dab8bf274bfb140e5f1df9321523d1275178a/backend/users/saml.py#L3-L7

Which would explain the issue. If true, this should be easy to fix (in the function I cite here).

For a proper fix, we should also add a migration to retroactively add any existing SAML users to the group.
