### ISSUE TITLE
Scans no longer showing up

### ISSUE THREAD

**Issue by Meesch** [UUDigitalHumanitieslab/I-analyzer#1278]
Pushing the 'scan' button just brings up the entry, not the scan:
<img width="788" alt="Screenshot 2023-10-04 at 16 55 31" src="https://github.com/UUDigitalHumanitieslab/I-analyzer/assets/31687030/4a23ab8a-59b3-48a1-ac3f-1357c073d0a0">

And there is no tab with the scan visible:
<img width="824" alt="Screenshot 2023-10-04 at 16 56 27" src="https://github.com/UUDigitalHumanitieslab/I-analyzer/assets/31687030/fa923830-a54f-4bcc-b864-91de774db2e8">

Any idea why this happens? Happens for both the Times and the Periodicals corpora.

**Comment by lukavdplas** [comment]
https://github.com/UUDigitalHumanitieslab/I-analyzer/blob/bf7dab8bf274bfb140e5f1df9321523d1275178a/frontend/src/app/document-view/document-view.component.html#L32-L34

https://github.com/UUDigitalHumanitieslab/I-analyzer/blob/bf7dab8bf274bfb140e5f1df9321523d1275178a/frontend/src/app/document-view/document-view.component.ts#L47-L49

Looks like the tab is hidden based on `scan_image_type`, though that value looks to be correct in the API on production. Mysterious.
