### ISSUE TITLE
Update index mappings

### ISSUE THREAD

**Issue by BeritJanssen** [UUDigitalHumanitieslab/I-analyzer#1281]
In order to optimally use the new highlighting functionality, the existing corpora need to be re-indexed. To ease the process of updating this, only a single change needs to be made to the corpus definition, i.e. the setting updated_highlighting needs to be set to True in the main_content_mapping method, see example below for the speech field in parliamentary corpora:

`es_mapping = main_content_mapping(token_counts=True, stopword_analysis=True, stemming_analysis=True, updated_highlighting=True)`

This needs to be updated for all corpora that we deem interesting/functional enough to have this functionality (and locally tested with a test set), pushed to acceptation/test/production, and then the corpus needs to be re-indexed. The progress on the corpora will be tracked here:

- [x] DBNL (+ reindex to ES8)
- [x] Dutch Annual Reports
- [x] Dutch Newspapers Public
- [x] ECCO
- [ ] FIJI (replacement of JewishInscriptions) -> depends on #1288 
- [x] Goodreads
- [x] Guardian-Observer
~~- [ ] Jewish Inscriptions~~ -> FIJI
- [x] Periodicals
- [x] Rechtspraak
- [x] Times -> failed halfway, restarted with smaller batch size ("size": 100 works)
- [x] Troonredes

Update: for all corpora, updated mappings have been added. Pending reindexing operations.

**Comment by lukavdplas** [comment]
See #1285 - can you please add some context about the how + why? This issue would be impossible to pick up for another developer.

**Comment by BeritJanssen** [comment]
I added the description from #1285 here. I just needed an issue to track the work I'd already been doing.

**Comment by BeritJanssen** [comment]
@Meesch , I just set the `updated_highlighting=True` as a new global default on the concerning branch (https://github.com/UUDigitalHumanitieslab/I-analyzer/tree/feature/corpus-updates)
