### ISSUE TITLE
visualization.query functions concerning date incorrect

### ISSUE THREAD

**Issue by BeritJanssen** [UUDigitalHumanitieslab/I-analyzer#1287]
While looking for the bug causing #1043 I saw two functions concerning date fields which look suspicious:
https://github.com/UUDigitalHumanitieslab/I-analyzer/blob/e14bed8d6b0b13b3691a1bc59259df63fc2dab51/backend/visualization/query.py#L134
https://github.com/UUDigitalHumanitieslab/I-analyzer/blob/e14bed8d6b0b13b3691a1bc59259df63fc2dab51/backend/visualization/query.py#L148

This setup would break the functionality in `ngram.get_total_time_interval` to narrow down the time interval for corpora whose date fields are not called 'date'.

**Comment by lukavdplas** [comment]
Yup, that's a mistake.

This should look for a `range` filter that specifies a `format`, e.g.:

```py
{
    'range': {
        _: {
           'format': ...
           ...
        }
    }
}
```
