### ISSUE TITLE
standardised nested date mapping

### ISSUE THREAD

**Issue by lukavdplas** [UUDigitalHumanitieslab/I-analyzer#1292]
Proposed solution for various issues surrounding date fields, including:
- Mixed precision levels which would complicate https://github.com/UUDigitalHumanitieslab/I-analyzer/issues/992
- https://github.com/UUDigitalHumanitieslab/I-analyzer/issues/1114
- The awkward UI of having four (!) date pickers for "earliest earliest date", "latest earliest date", etc.

I would propose using a single nested field mapping for all date fields. For instance, we can use four subfields:

- `exact`: the exact day, if known
- `year`: the exact year, if known
- `lower`: lower bound for the date
- `upper`: upper bound for the date

`exact` and `year` would not always be filled in, of course, but you could make it so the "less precise" values are inferred. (Either during data entry or by elasticsearch.) So in a corpus with exact dates, you could still request `date.year`, `date.lower` and `date.upper`.

Thus, a date filter for 1800-1900 would look something like the following:

```json
{
	"range": {
		"date.lower": {
			"gte": "1800-01-01",
			"format": "yyyy-MM-dd"
		},
		"date.upper": {
			"lte": "1900-01-01",
			"format": "yyyy-MM-dd",
		}
	}
}
```

Which should work on any corpus with a `date` field, regardless of precision.

There is a broader question whether standardising corpus fields is a good idea (c.f. https://github.com/UUDigitalHumanitieslab/I-analyzer/issues/993), but then date fields are already "lightly" standardised by being referenced in the corpus metadata.

**Comment by lukavdplas** [comment]
I think you would also need `date.estimate` or such for to make histograms. (If you only know a range, that is just the middle point.)

**Comment by BeritJanssen** [comment]
I like it!

**Comment by BeritJanssen** [comment]
How about we only introduce this date field for the corpora for which the estimates apply? That would mean we'd need to check in the frontend on whether or not the date field has subfields, but it would also save some reindexing hassle.

**Comment by lukavdplas** [comment]
It would be the most urgent for those corpora, but the main advantage would be that you could have a unified query format for all corpora.  Especially relevant for #992

**Comment by lukavdplas** [comment]
But since we currently do not have a unified format, it's not an issue to let a "new" mapping exist alongside a deprecated one. In the case of corpora like sweden-old, the new format would still be an improvement.

**Comment by BeritJanssen** [comment]
Some updates after experimentation: the field we probably want to use here is the [Object field type](https://www.elastic.co/guide/en/elasticsearch/reference/current/object.html). Other than a multifield, it allows throwing multiple values at it. So an indexing operation would become:
```
PUT testcorpus/_doc/1
{
  "date.year": "2010",
  "date.estimate": "2010-06-30",
  "date.earliest": "2001-01-01",
  "date.latest": "2020-12-31"
}
```
The query should always be performed on the `date.estimate` field, as we cannot pass multiple fields in a range query. It also makes more sense that way, as then we don't *need* to make up a `date.earliest` and `date.latest` field if we have an exact date. With an exact date, we would simply set `estimate = exact`, and if we only have a year field, we set `estimate = yyyy-01-01`, or something along those lines. And if we have earliest/latest fields, we set the estimate to a value in between. Does this sound like a good strategy?

**Comment by lukavdplas** [comment]
Thanks for looking into this!

> The query should always be performed on the date.estimate field, as we cannot pass multiple fields in a range query.

This seems like an issue to me. In the example you gave, if I'm searching for documents up to 2005, I would want that one to be included.  (I'm sure there are also cases where you would want stricter searching. You could include strict vs. lenient as an option to the filter.) Users currently have the option to search like that in corpora with date ranges.

That said, I don't think it's really a problem if a single `Filter` object in the frontend translates to two elasticsearch filters (i.e. one for the `earliest` field and one for the `latest` field). Our current implementation does assume that, but it should not be so difficult to adjust.

> It also makes more sense that way, as then we don't need to make up a date.earliest and date.latest field if we have an exact date. 

I suppose that would be true if you would not use earliest/latest for querying, as you propose.

**Comment by BeritJanssen** [comment]
I'm now moving away from the [object field type](https://www.elastic.co/guide/en/elasticsearch/reference/current/object.html). A multifield is not an option: using a date string as an input value and mapping it to an integer is not what multifields were designed for. Perhaps, an ingest pipeline with a custom analysis script which will map the input to year integer / date internally could make this work, but trying this will take time and may in the end amount to nothing.

The object field type would work, but comes with disadvantages:
- the current date field validator fails, and the object field type is too loose to write a proper validation against
- as stated above, it requires reindexing.

What I would propose instead is the following:
- for all corpora with approximate dates, we introduce the following fields
- date_earliest
- date_latest
- date
The description of the `date` field should be explicit about that it is an *estimate*. This field will solely be used for the frontend filter, whereas constructing the Elasticsearch filter will done by the backend. The backend will then check if there are `date_earliest / date_latest` fields present, and if so, do a composite `must` query which filters on these fields instead. Does this sound like a solution?
Advantage:
- no need to reindex corpora with "normal" date fields
- we can still introduce a `date` field across all indices

A problem which does remain is that Elasticsearch date fields cannot handle years lower than year 1. So for some of the inscription corpora (with year estimates 0 and lower), we still cannot provide a proper date filter.

**Comment by lukavdplas** [comment]
In cross-corpus search, what would a query look like if it's filtering one corpus with exact dates and one corpus with date ranges?

**Comment by BeritJanssen** [comment]
Argh, good point, that. Didn't think of the cross-corpus situation: then we'd filter on date estimates in this case, which may not be what the user wants in all cases. That means we do indeed need date_earliest / date_latest fields on *all* corpora.

**Comment by lukavdplas** [comment]
Yes, that was kind of why I proposed this.

Regarding re-indexing:
- We won't build cross-corpus search anytime soon, and it would be fine to introduce a "new date field" alongside the old one.
- I cannot imagine we'll get user-friendly cross-corpus search _without_ reindexing most corpora. Stuff like making sure the same "concept" is under the same field name, or fields with the same name have the same mapping.

**Comment by BeritJanssen** [comment]
My proposal would then, still, be, to add *new flat fields* over adding a very complex "object type" field. I expect that retrieval will be faster that way, and we could even do this with an update script if we wanted.

**Comment by BeritJanssen** [comment]
I was also wondering about field naming conventions. We often choose the underscore for "Pythonic" reasons. Should we internally decide on a convention, or would this just make the application cumbersome to adapt for other developers? I can imagine field names such as `date:later` (`date.later` would mean Elasticsearch goes to assume object type), but right now, field names are a slug field, which means we cannot use anything but `-_[Aa-Az][0-9]` in the field names.

**Comment by lukavdplas** [comment]
Btw, did you look at [date_range fields](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/range.html)?

Naming conventions are fine if you're managing your index from I-analyzer. Right now, you could also connect to an existing index, but ideas like this issue would make that problematic anyway.

**Comment by BeritJanssen** [comment]
Good find! This may be what we want, since it allows a simple `date_range` query. This means that the date field could have two different mapping types underlying, but that we can search over them in the same way.
