### ISSUE TITLE
`similarity-chart.component`: support gaps in word model data

### ISSUE THREAD

**Issue by BeritJanssen** [UUDigitalHumanitieslab/I-analyzer#1301]
Right now, word model visualizations will be off if there are gaps in the word model data:
![Regierung updated WEMs](https://github.com/UUDigitalHumanitieslab/I-analyzer/assets/11174072/20531c20-71cb-4bf7-a0e8-3554a7eb02b9)

We should make sure there are no superfluous lines in the line graphs, so the `similarity-chart.component` can display word models even if there are gaps in the data. Perhaps it's also a good idea to break the line graphs in that case, to indicate that gap.

**Comment by lukavdplas** [comment]
That screenshot suggests that there may be an error in the data passed on the graph, namely:
- more than one value per series per time interval
- non-monotonic X values in a dataseries

**Comment by lukavdplas** [comment]
Re. your point about bridging gaps: [the configuration of the similarity chart](https://github.com/UUDigitalHumanitieslab/I-analyzer/blob/2285937f2498e56e20eac9138379ffe2e9dbaf0a/frontend/src/app/word-models/similarity-chart/similarity-chart.component.ts#L182-L238) is indeed such that it will show not connect over gaps in the data.

A dataset like this would be displayed with a gap:

```ts
chart.data = {
    labels: ['1800', '1810', '1820', '1830'],
    datasets: [{
        data: [0.5, 0.5, null, 0.5]
    }]
}
```

This, however, will not:

```ts
chart.data = {
    labels: ['1800', '1810', '1830'],
    datasets: [{
        data: [0.5, 0.5, 0.5]
    }]
}
```

From the chart, I would say the data of this graph looks more like this:

```ts
chart.data = {
    labels: ['1800', '1810', '1820', '1830', '1800', '1810'],
    datasets: [{
        data: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
    }]
}
```

**Comment by BeritJanssen** [comment]
In fact, I believe the artifact may just have been caused by the dataset being shuffled - later time windows appearing later in the arrays. This occurred with non-duplicate values in another dataset where the earliest time windows appeared last in the data - this, in turn, was caused by slight name differences in the older files. The word models should do some sorting prior to sending data to the frontend then.
