### ISSUE TITLE
Should field "role" be called "speech_type" in ParliamentCanada?

### ISSUE THREAD

**Issue by BeritJanssen** [UUDigitalHumanitieslab/I-analyzer#1304]
While going over user warnings, I noticed that there is a field "role" in `corpora/parliament/canada.py` which is filled with information from the field `speech_type`, which, at least in the test data, contains values such as `Interjection`. Perhaps the full data contains other values in this field, which made this a conscious choice? Otherwise, this field should be renamed.

Fixing this in the index would require a reindex though, either from source or with a script to move the data.

**Comment by lukavdplas** [comment]
It contains both speech types and parliamentary roles:

![histogram of "role" field](https://github.com/UUDigitalHumanitieslab/I-analyzer/assets/43678097/5dcc2a84-eb01-4051-9e85-e9d6164dd5c9)

**Comment by BeritJanssen** [comment]
I don't think we can fix this then, given the raw data contains mixed information. The field name is fine then.
