### ISSUE TITLE
Presentation of multilingual fields

### ISSUE THREAD

**Issue by BeritJanssen** [UUDigitalHumanitieslab/I-analyzer#1305]
For the Peaceportal corpora, I had to tackle #1106 . These corpora may have transcriptions in different languages (e.g., English or German). Right now, the transcriptions are indexed as `transcription_german`, next to a main `transcription` field. Then, all language specific fields are hidden for the frontend -- they will be searched, but the user only ever gets to see the (unanalyzed) transcription field. This means that highlighting won't work for stemmed / complex queries.

An alternative idea I had was to make the common "transcription" (or "speech") field `indexed=False`, but make this the only field that is shown to the user, and devise a mechanism by which the "parent" field displays contents from the language specific fields here instead. On Elasticsearch level, this would be quite easy to tackle with searching in a `transcription*` field, but I cannot oversee the complexity of required frontend changes to make this work.

**Comment by lukavdplas** [comment]
Small point: I would strongly recommend using ISO codes in fieldnames, e.g. `de` rather than `german`.

A method I've seen is to use nested fields, e.g. a german source document would look like this:

```json
{
	"transcription": {
		"de": "Some text in german",
		"en": null,
	}
}
``` 

And an English one like this:

```json
{
	"transcription": {
		"de": null,
		"en": "Some text in English",
	}
}
``` 

This makes it trivial to set language-specific analysers for each subfield. If needed, you could still make a scripted or unindexed with the unanalysed text, but you may not need it.

**Comment by BeritJanssen** [comment]
Oh yes, you brought this up before. I did look into nested fields, but it seems you need to query them with a specific `nested` query: [ES documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html), and they are generally not encouraged by Elasticsearch. Do you perhaps mean [flattened fields](https://www.elastic.co/guide/en/elasticsearch/reference/current/flattened.html)? I just followed through on a link and thought that this looks perhaps more like what you had in mind.

**Comment by lukavdplas** [comment]
Oh, I wasn't aware of the performance issue, thanks for looking into it!

**Comment by lukavdplas** [comment]
A possible issue with searching for `transcription*` is that it is plausible you'll have unrelated fields with the pattern `transcription_something`. (E.g. `speech_type` in the parliament corpora follows this pattern.) 

So you would either need to:
- add validation to forbid this and re-index any existing corpora that use names like this.
- explicitly declare language variants in the corpus definition and search for them without a wildcard.

**Comment by lukavdplas** [comment]
Oh by the way, if you're creating an index for this, could you add a field with the ISO code? C.f. https://github.com/UUDigitalHumanitieslab/I-analyzer/issues/795 You can hide the field, it's more for compatibility with future language-related features.
