### ISSUE TITLE
update angular

### ISSUE THREAD

**Issue by lukavdplas** [UUDigitalHumanitieslab/I-analyzer#1329]
[documentation for primeng v14](https://www.primefaces.org/primeng-v14-lts/) (the version we use) shows a moving, undismissable banner about how we're not licensed to use it anymore - or at least the language is intended to suggest that. Anyway, we should probably do something about it - if nothing else, it does achieve the desired effect of making the documentation hostile to use.

The quick solution is to upgrade angular and primeng (which depends on angular). Though I would personally support moving toward a component library that doesn't pull stunts like this.

**Comment by JeltevanBoheemen** [comment]
Moving component libraries (while I agree with your sentiment) is a vast operation in such a big application, with no visible benefit to the end user. I would argue we have had enough of those for the time being :)
I'm upgrading Angular to fix the problems at hand.

**Comment by lukavdplas** [comment]
Yeah, that's definitely not a priority.

**Comment by lukavdplas** [comment]
I don't disagree, but what would we use instead? Add more of our own generic components like the dropdown or tabs component? Add a second component library?

There is a more general discussion that may be had in our team re. new applications (where you don't have this vendor lock-in problem); that's beyond the scope of this issue, but it may inform our choice here.

**Comment by ar-jan** [comment]
Any news on upgrading Angular? I took a look and saw some issues with dependencies that I'm not yet familiar with, and also some problem with an import containing `NgxScrollPositionRestorationModule` ([not compatible](https://github.com/TheJLifeX/ngx-scroll-position-restoration/issues/1) with Angular v17?).

**Comment by JeltevanBoheemen** [comment]
Yeah, the scroll position is what's blocking an update so far. I have yet to get around to forking that library and publishing a angular 13+ compatible version.
