### ISSUE TITLE
Search history broken

### ISSUE THREAD

**Issue by lukavdplas** [UUDigitalHumanitieslab/I-analyzer#1337]
### What went wrong?

The search history page did not load. Error message in console:

```
Uncaught (in promise): TypeError: right-hand side of 'in' should be an object, got undefined
```

### What did you expect to happen?

The page should have loaded.

### Screenshot

![screenshot showing empty page](https://github.com/UUDigitalHumanitieslab/I-analyzer/assets/43678097/6d0e3484-16f6-47df-9fae-3bc984f1ef76)

### Where did you find the bug?

- https://ianalyzer.hum.uu.nl
- https://peopleandparliament.hum.uu.nl

### Version

5.2.0

### Steps to reproduce

After logging in, go to `/search-history`

I've seen this on multiple servers, but I couldn't reproduce it locally, even when switching to the 5.2.0 version. Not sure what causes the difference.

**Comment by BeritJanssen** [comment]
The search history also doesn't work in version 5.1.0. Annoying that it cannot be reproduced locally, so git-bisect is not an option.
