### ISSUE TITLE
Search field obscures navbar dropdown

### ISSUE THREAD

**Issue by lukavdplas** [UUDigitalHumanitieslab/I-analyzer#1351]
### What went wrong?

When using the user dropdown in the search page, the search section is positioned _over_ the dropdown.

This happens because the search section has a z-index of 1000.

### What did you expect to happen?

The dropdown should always appear on top.

### Screenshot

![screenshot showing the user dropdown covered by the background over the search section](https://github.com/UUDigitalHumanitieslab/I-analyzer/assets/43678097/7cd658a6-35ca-4f0a-895d-86fa9d7a877c)

### Where did you find the bug?

- [X] https://ianalyzer.hum.uu.nl
- [ ] https://peopleandparliament.hum.uu.nl
- [ ] https://peace.sites.uu.nl
- [ ] a server hosted elsewhere (i.e. not by the research software lab)
- [X] a local server

### Version

5.3.0

### Steps to reproduce

- Log in
- Go to the search page for a corpus
- Open the user dropdown (top right)

**Comment by JeltevanBoheemen** [comment]
@lukavdplas Do you remember why you added the `z-index` for `.search-section`? It seems just removing this CSS property has no negative consequences and resolved this bug. But I might overlook something.

**Comment by lukavdplas** [comment]
If I'm blamed on git, I think that's just because I refactored the old code.

I _think_ this has to do with the sticky-top effect for the pagination controls? But it's quite possible this is just not needed. I-analyzer is old enough that we sometimes have CSS rules that just don't do anything anymore.
