### ISSUE TITLE
Angular lifecycle conflict

### ISSUE THREAD

**Issue by JeltevanBoheemen** [UUDigitalHumanitieslab/I-analyzer#1365]
**Is your feature request related to a problem? Please describe.**
Angular linting complains about lifecycle conflict: in `visualization/visualization.component.ts`

```
   27:16  error  Implementing DoCheck and OnChanges in a class is not recommended          @angular-eslint/no-conflicting-lifecycle
   27:25  error  Implementing DoCheck and OnChanges in a class is not recommended          @angular-eslint/no-conflicting-lifecycle
  115:5   error  Declaring ngDoCheck and ngOnChanges method in a class is not recommended  @angular-eslint/no-conflicting-lifecycle
  121:5   error  Declaring ngDoCheck and ngOnChanges method in a class is not recommended  @angular-eslint/no-conflicting-lifecycle
```

**Describe the solution you'd like**
Resolve these (justified) errors. Should implement with either `DoCheck` or `OnChanges`, not both.

**Comment by lukavdplas** [comment]
The `VisualizationComponent` uses some convoluted logic to control the loading spinner for visualisations. It acts as a parent for individual visualisation components and only shows one at a time. Visualisation components all have their own loading state and provide that as an output to their parent. Those outputs are used to update a single boolean member of the  `VisualizationComponent` , which uses it to set the css class `is-loading` on a container element of the visualisation.

This merging of several child outputs into a single variable is implemented in a weird way; that's where the `ngDoCheck` happens. You _could_ improve that logic by using something more rxjs-y, but there really isn't any reason to keep a centralised loading state.

Suggestion: don't provide the loading state as an output of each visualisation, don't keep track of it in the `VisualizationComponent`, and just use [hostbinding](https://angular.io/api/core/HostBinding) to directly set the `is-loading` class on the visualisations.
