### ISSUE TITLE
Show a hint for ngram visualisation without query

### ISSUE THREAD

**Issue by Meesch** [UUDigitalHumanitieslab/I-analyzer#1371]
Currently, if the user has not put in a query, the n-gram visualisation is completely hidden. I think it might be a good idea to not hide it, but instead prompt the user to put in a query first. What do y'all think?

**Comment by lukavdplas** [comment]
I think the logic of hiding was that the visualisation is an answer to a question that the user is not asking.

But it's not very clear - I would suggest showing a disabled option in the dropdown with a tooltip explaining why it's not available. I wouldn't prompt users.

The same goes for the frequency of the search term visualisation, by the way.

**Comment by lukavdplas** [comment]
closed by #1467
