### ISSUE TITLE
Never-ending NLTK data check

### ISSUE THREAD

**Issue by lukavdplas** [UUDigitalHumanitieslab/I-analyzer#1377]
### What went wrong?

Running `yarn start` from the repository root completely floods my terminal with 

```
[nltk_data] Downloading package stopwords to /home/luka/Documents/I-an
[nltk_data]     alyzer/I-analyzer/backend/addcorpus/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
```

repeated ad infinitum.

I did not get the same issue when running `yarn start-back` and `yarn start-front` in separate terminals, though.

This isn't really a big deal but the command is kind of useless for development if it does not give sensible terminal output.

### What did you expect to happen?

Strictly speaking, you would only need to check the nltk data once during startup, but it's possible that happens during runtime too. In case, when starting up the application, I would expect to see this message only once.

Perhaps the download (or verification that a download is not necessary) actually does happen only once and this is just some annoying interaction between the frontend and backend output.

### Screenshot

![screenshot of terminal showing the quoted message being repeated many times](https://github.com/UUDigitalHumanitieslab/I-analyzer/assets/43678097/249d4603-8bcc-4bfd-ba96-d7da418f585e)

### Where did you find the bug?

- a local server

### Version

develop at 7170f219453f9cee71112f5b3b9ad589ecba9f93

### Steps to reproduce

Start a development server by running `yarn start` from the repository root.

**Comment by JeltevanBoheemen** [comment]
Perhaps [configuring livereload](https://github.com/tjwalch/django-livereload-server) with `--ignore-file-extensions` will work? Though it doesn't appear I run the `python manage.py livereload` in normal dev circumstances.
