### ISSUE TITLE
tag requests + document IDs containing slashes = carnage

### ISSUE THREAD

**Issue by lukavdplas** [UUDigitalHumanitieslab/I-analyzer#1380]
### What went wrong?

I'm having some trouble with my development environment (since today).

Most notable:
- Frequent crashes: failing request, terminal flooded with errors, etc.
- Shutting down the frontend before the backend can cause the backend to freeze my machine. Didn't try it the other way around.

### What did you expect to happen?

None of the above.

### Screenshot

![screenshot of terminal](https://github.com/UUDigitalHumanitieslab/I-analyzer/assets/43678097/3aa062dc-20f1-4af9-b2d1-90103421b0d5)

Console output:

![screenshot of browser console](https://github.com/UUDigitalHumanitieslab/I-analyzer/assets/43678097/547ebc46-9abd-4cf2-8154-879190afe8a7)

### Where did you find the bug?

-  local server

### Version

develop at 7170f219453f9cee71112f5b3b9ad589ecba9f93

### Steps to reproduce

On my PC, i can reliably reproduce the issue as follows:

- start elasticsearch, start the backend with `yarn start-back`, and the frontend with `yarn start-front`
- open https://localhost:4200
- navigate to a corpus, then back the home page, then back to a corpus, then back the the home page again
- the page is extremely slow to load the list of corpora and often fails to load images
- after about 30 seconds, the backend terminal will start flooding errors (screenshot above)

But I'm not confident you'd get the same effect on another machine.

I updated python to 3.9 (from 3.8) this morning, which may be what causes the issue?

**Comment by Meesch** [comment]
Yes, I did have this issue, but specifically with the parliament-uk corpus!

**Comment by lukavdplas** [comment]
Hm, that's what I was using here too, but I didn't check if it was corpus-specific.

One thing that stands out to me in the terminal output above is the request to `/api/tag/document_tags/parliament-uik/uk.org.publicwhip/debate/2002-12-19.9.88.0`. To my knowledge, the route is structured `/api/tag/document_tags/{corpus}/{document_id}

So the ID of this document would be `uk.org.publicwhip/debate/2002-12-19.9.88.0` - but the slashes might be causing issues for routing.

None of that should crash the server like this, though, it should just show an error.

**Comment by lukavdplas** [comment]
Looks like that is indeed the problem. Working on a fix!
