### ISSUE TITLE
yarn commands inconsistent

### ISSUE THREAD

**Issue by lukavdplas** [UUDigitalHumanitieslab/I-analyzer#1396]
This issue only affects develop environments.

Minor annoyance:

- `yarn start-front` is not equivalent to `cd frontend && yarn start` (the latter also runs tests)
- `yarn test-front` is not equivalent to `cd frontend && yarn test` (the latter reruns tests after file changes)

**Comment by BeritJanssen** [comment]
Adding to this issue:
- `yarn test` runs with `--sourceMap=false`, which is not what you want when debugging a test in the browser dev tools. Perhaps we can add some more flavours for the `test` command here.

**Comment by jgonggrijp** [comment]
Why not just remove the `--sourceMap=false`? I don't think there is any scenario in which one might want to run tests without source maps.

**Comment by BeritJanssen** [comment]
I came to the same conclusion. They may have been removed to speed up testing on GitHub, so before changing, we should still ascertain these use the correct command.
