### ISSUE TITLE
Streamline responses from visualization endpoint

### ISSUE THREAD

**Issue by BeritJanssen** [UUDigitalHumanitieslab/I-analyzer#1401]
The responses from the visualization endpoint can be quite different, e.g.,
```
{
  time_points: ['1900-1920', '1940-1960'],
  words: [ {}, {} ]
}
```
compared to
[
  { key: '1900-1920', token_count: ... },
  { key: '1920-1940', token_count: ...}
]

Of course it makes sense that different visualizations have different arguments, but perhaps the setup of an array of objects, with 'key' indicating x axis ticks could become a convention? Or would that mean uncomfortable data wrangling for the joyplot, @lukavdplas ? Having similar formats will also help with documentation and support, should we tackle #1391 .

**Comment by lukavdplas** [comment]
I think the joyplot already does quite a bit of data wrangling. A long-format array of values sounds fine.

In the long term, https://github.com/UUDigitalHumanitieslab/I-analyzer/issues/1340 would suggest a different approach to a visualisation API, though I could imagine implementing both endpoints.

**Comment by BeritJanssen** [comment]
Ah, I forgot about #1340. As this issue doesn't have high urgency, let's indeed adopt the vega format.
