### ISSUE TITLE
Outfactor source extraction functions

### ISSUE THREAD

**Issue by lukavdplas** [UUDigitalHumanitieslab/I-analyzer#1429]
### Discussed in https://github.com/UUDigitalHumanitieslab/I-analyzer/discussions/1428

<div type='discussions-op-text'>

<sup>Originally posted by **lukavdplas** October 16, 2023</sup>
Amongst other things, I-analyzer contains the functionality to convert XML, HTML or CSV files to a flat collection of key/value pairs. To extract these, you essentially pass on a few parameters and a list of `Extractor` objects. This functionality could be outfactored into an independent python package.

The package would essentially contain:

- `XMLReader` / `HTMLReader` / `CSVReader` classes, which implement the `source2dicts` function we now have in `CorpusDefinition`
- The `Extractor` classes

Individual corpus definitions in the I-analyzer backend would look pretty much the same, but the `CorpusDefinition`  child classes would be more lightweight.</div>

Note: moving this discussion to an issue because I was using the issue to track my work for the coming weeks.

**Comment by BeritJanssen** [comment]
Ah, right, I thought that it would be good to discuss this wrt #1078 : how can we set up a pipeline to harvest data & update the index?

**Comment by lukavdplas** [comment]
If we ever get funding for that issue, I think there should indeed a discussion about how and where to implement preprocessing.

In the short them, the package is intended as a preparation for allowing data-based corpus definitions #978. It allows researchers to use our pre-processing library to do that step themselves, and then provide a corpus definition that doesn't need to contain complex data wrangling functions.

At the moment, the ianalyzer-readers package is an outfactor of _existing_ functionality. It lack polish but it's fully functional. I agreed with @JeltevanBoheemen that we should integrate it in I-analyzer asap, to avoid parallel development issues like this one https://github.com/UUDigitalHumanitieslab/I-analyzer/pull/1392#issuecomment-1908160539
