### ISSUE TITLE
Bar charts get stuck

### ISSUE THREAD

**Issue by BeritJanssen** [UUDigitalHumanitieslab/I-analyzer#1453]
### What went wrong?

Bar charts don't seem to compute on the current version.

### What did you expect to happen?

I expected a bar chart to be computed. But both document and term frequency just show a spinner of death.

### Screenshot

<img width="1455" alt="Screenshot 2024-02-15 at 12 18 07" src="https://github.com/UUDigitalHumanitieslab/I-analyzer/assets/11174072/c6afdd09-0cc3-482f-a35a-133c4240b0f7">

### Where did you find the bug?

- [X] https://ianalyzer.hum.uu.nl
- [ ] https://peopleandparliament.hum.uu.nl
- [ ] https://peace.sites.uu.nl
- [ ] a server hosted elsewhere (i.e. not by the research software lab)
- [ ] a local server

### Version

5.4.0

### Steps to reproduce

Enter search term, request document or term frequency visualization.

**Comment by BeritJanssen** [comment]
This seems fixed on develop.

**Comment by lukavdplas** [comment]
Fixed as of 5.5.0
