### ISSUE TITLE
Protocol Buffers for interchange server/client

### ISSUE THREAD

**Issue by oktaal** [UUDigitalHumanitieslab/I-analyzer#147]
Using Protocol Buffers it is possible to specify the data structure in one spot and have it used both in the server [(Python tutorial)](https://developers.google.com/protocol-buffers/docs/pythontutorial) and on the client [(JavaScript/TypeScript implementation)](https://github.com/dcodeIO/ProtoBuf.js/). Currently we have this structure defined in two spots: `web.py` for the server and `api.service.ts` for the client.

**Comment by lukavdplas** [comment]
I think this discussion was more relevant when I-analyzer was in early development. Changing this is a lot less rewarding if you already have an API with models in two languages.
