### ISSUE TITLE
Hide tag features for unauthenticated users

### ISSUE THREAD

**Issue by BeritJanssen** [UUDigitalHumanitieslab/I-analyzer#1483]
**Is your feature request related to a problem? Please describe.**
As we implement #988 , we want to hide the following from unauthenticated users:
- TagFilter
- Tag control in DocumentView

Under the hood, a `FoundDocument` fetches the tags connected to a document, which we would want to avoid (as it predictably fails) for unauthenticated users.

**Describe the solution you'd like**
`QueryModel` and `FoundDocument` need to be adjusted such that the logic related to tags is switched on or off, depending on whether or not we are dealing with an authenticated user.

**Describe alternatives you've considered**
Rewrite I-Analyzer from scratch (not really though)

**Comment by lukavdplas** [comment]
> Under the hood, a FoundDocument fetches the tags connected to a document, which we would want to avoid (as it predictably fails) for unauthenticated users.

It will only do that if you add an observer (in a template), so this request would also be avoided by hiding the UI. That's a bit of a backwards solution, though: you would expect the model to tell the template whether tagging is possible.
