### ISSUE TITLE
Infer upper/lower for RangeFilter and DateFilter

### ISSUE THREAD

**Issue by JeltevanBoheemen** [UUDigitalHumanitieslab/I-analyzer#1535]
**Is your feature request related to a problem? Please describe.**
RangeFilter and DateFilter **require** an upper and lower. These are not supplied in JSON corpora.

**Describe the solution you'd like**
Those should be inferred after indexing, using an ES request to determine the values.

**Describe alternatives you've considered**
An alternative would be to supply these manually in the corpus definition. This requires more work for the user.

**Comment by lukavdplas** [comment]
Another alternative is to query upper/lower bounds when you load the filter in the interface. The MultipleChoiceFilter (keyword filter) does something similar (requesting a list of values).
