### ISSUE TITLE
Endless `formatInnerHtml` loop

### ISSUE THREAD

**Issue by BeritJanssen** [UUDigitalHumanitieslab/I-analyzer#1543]
### What went wrong?

During debugging for #956 I put a breakpoint in `document-view.component.formatInnerHtml`, and noticed that the template keeps triggering the function, so that every field is processed endlessly. The call stack indicates that the `RouterStoreService` is responsible. We still seem to have a feedback loop.

<img width="217" alt="Screenshot 2024-04-12 at 15 02 47" src="https://github.com/UUDigitalHumanitieslab/I-analyzer/assets/11174072/f245bb18-c268-424a-ba6d-de5786d95208">

### What did you expect to happen?

I expect that this function would be triggered *once* for each field.

### Where did you find the bug?

- [ ] https://ianalyzer.hum.uu.nl
- [ ] https://peopleandparliament.hum.uu.nl
- [ ] https://peace.sites.uu.nl
- [ ] a server hosted elsewhere (i.e. not by the research software lab)
- [X] a local server

### Version

develop

### Steps to reproduce

Start up I-Analyzer, navigate to a corpus, put a breakpoint on line 108 of `document-view.component.ts`, and open a document view.

**Comment by lukavdplas** [comment]
Strange, I can see the repeated calls to `formatInnerHTML`, but I can't find any repeated calls within `RouterStoreService`. Can you give more information about what you noticed there?
