### ISSUE TITLE
Make URL fields clickable links

### ISSUE THREAD

**Issue by Meesch** [UUDigitalHumanitieslab/I-analyzer#1583]
<img width="769" alt="Screenshot 2024-05-21 at 13 54 20" src="https://github.com/UUDigitalHumanitieslab/I-analyzer/assets/31687030/82b9ce70-d4c0-4789-b11a-89b34d16ff13">

Let's create a functionality where we can mark certain fields as 'url_fields', and make those fields clickable links in the fronend. ElasticSearch does not have a native url_mapping, instead we store these as keyword fields usually. Tijmen and I think the easiest solution would be to add a parameter in the frontend for url fields.

**Comment by lukavdplas** [comment]
> Let's create a functionality where we can mark certain fields as 'url_fields'

Did you try `display_type = 'url'`?
