### ISSUE TITLE
Bug: cannot create new index / will write to wrong index version in production

### ISSUE THREAD

**Issue by BeritJanssen** [UUDigitalHumanitieslab/I-analyzer#1656]
Currently, it's not possible to index a new corpus in production as far as I can tell. This line seems to be the culprit:
https://github.com/UUDigitalHumanitieslab/I-analyzer/blob/14c6817093a7d232c2c933a0dd9910fb22f44b4a/backend/es/es_index.py#L75

This used to be
```
corpus_definition.es_index = "{}-{}".format(
            corpus_definition.es_index, get_new_version_number(client, alias, corpus_definition.es_index))
```
which means the corpus_definition object was updated, so retrieving `corpus_definition.es_index` in the `populate` method would return the versioned index name.

I suspect that if we try to create a new version of an existing corpus with versioned index `myindex-1` and alias `myindex`, we can neatly create the `myindex-2` corpus, but write to `myindex-1` instead, as the `populate` method writes to the alias `myindex`, which still points to `myindex-1`.

Possible solutions:
- easiest: let `create` return the versioned index name, and pass this into to the `populate` method
- go back to `corpus_definition.es_index = versioned_index`, followed by `corpus_definition.save()`
- add a new field `es_index_version` to the CorpusConfiguration model, which is updated with the number returned by `get_new_version_number()` method upon creation

Disadvantage of the last two approaches: in case the index operation fails, the database will show a version number which does not correspond to the version the alias points to. This could be mitigated by decrementing the version number upon failure.

**Comment by abdulrehman-code** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
