### ISSUE TITLE
Email address validation

### ISSUE THREAD

**Issue by ar-jan** [UUDigitalHumanitieslab/I-analyzer#1663]
The frontend components for registration and password reset reject valid email addresses (e.g. `.info` domain).

**Comment by lukavdplas** [comment]
Here's the issue:

https://github.com/UUDigitalHumanitieslab/I-analyzer/blob/d2ffc726a83a1d0d9cfe940a0d4630937ab1fd55/frontend/src/app/login/registration/registration.component.html#L27C124-L27C150

This regex pattern required that top-level domains are always 2 or 3 characters, which is indeed too strict.
