### ISSUE TITLE
Turn Guardian/Observer "source paper" field into keyword field

### ISSUE THREAD

**Issue by BeritJanssen** [UUDigitalHumanitieslab/I-analyzer#467]
This is probably done quickest after the index is complete in its current form using the Reindex api. Enables filtering / visualizing by source paper (i.e., Manchester/ London Guardian, Observer)

**Comment by lukavdplas** [comment]
closed by https://github.com/UUDigitalHumanitieslab/I-analyzer/commit/30c6aac438b9316fd47dc4fa21ef2733b2639b4f
