### ISSUE TITLE
Improve support for right-to-left languages

### ISSUE THREAD

**Issue by oktaal** [UUDigitalHumanitieslab/I-analyzer#48]
Currently absolutely minimal support is in place in the search highlighter. I couldn't get the test to work with wildcards or quotation marks, because the mixing of those symbols cause confusion. At the very least for the developer. This could definitely be improved, maybe by using native symbols from those writing systems or adding some mode support for switching direction.

**Comment by lukavdplas** [comment]
@Meesch now that the new highlighter is merged, can you see if this is resolved?

**Comment by Meesch** [comment]
Addressed by #1207
