### ISSUE TITLE
Avoid scientific notation in frequency table

### ISSUE THREAD

**Issue by lukavdplas** [UUDigitalHumanitieslab/I-analyzer#725]
Question from Ville Vaara:

> Can we lose the scientific notation in the table for? e-7 etc?

I agree that the table should not use scientific notation. I  _think_  this will not happen anymore after #723 , but I'm not sure. I should ask Ville for an example where this happens.

**Comment by BeritJanssen** [comment]
@lukavdplas can this be closed?

**Comment by lukavdplas** [comment]
this was requested by the p&p research group, so if they still expect this to be picked up in some way, then no. if they're happy with the current behaviour, then yes.

as far as general usability is concerned, i think the current behaviour is fine and we can close the issue.
