### ISSUE TITLE
Highlight stemmed matches

### ISSUE THREAD

**Issue by lukavdplas** [UUDigitalHumanitieslab/I-analyzer#807]
For corpora with a stemmed field, the results include stemmed matches, but the highlighter does not work for stemmed results. For example, here i am searching for "twist"

![image](https://user-images.githubusercontent.com/43678097/183597011-5711247b-9d90-49f6-8ded-0c6150455aad.png)

The first document is correctly returned, but not highlighted.

**Comment by lukavdplas** [comment]
@Meesch can we close this?

**Comment by Meesch** [comment]
adressed by #1207
