### ISSUE TITLE
Relevance score disappears from results page

### ISSUE THREAD

**Issue by Meesch** [UUDigitalHumanitieslab/I-analyzer#835]
The relevance score disappears from the results page when you sort the results by something other than relevance. This might have something to do with the fact that there is a new query created when sorting by a different metric. See if this is the case and find out if relevance is still retrievable somewhere in that query. If not, it is not the worst thing in the world, but I think it would be nice to have the relevance score visible at all times. 

My use case is that I wanted to filter by sequence so I could keep reading in order, but I still wanted to skip over the least relevant entries.

**Comment by BeritJanssen** [comment]
I think this can actually not be fixed in an easy way, as Elasticsearch won't return relevance scores for other sorting mechanisms. Perhaps can reopen this if a future Elasticsearch update changes this behaviour.
