### ISSUE TITLE
Changing the date filter

### ISSUE THREAD

**Issue by Meesch** [UUDigitalHumanitieslab/I-analyzer#879]
Currently, when one tries to change the date filter by typing in a date, one needs to 'deselect' the date field for the changes to be enacted. I think ideally, the user would press either tab or return to finalize the date and move on to the next date field (if the user is changing the first date field) or enact the new date filter (if the user is changing the second date field).

**Comment by lukavdplas** [comment]
This specific issue is addressed by #1142 - the date picker now reacts when you hit enter. Since #1139, filters will also not activate when they do not contain meaningful data.
