### ISSUE TITLE
use paramDirective for search filter components

### ISSUE THREAD

**Issue by lukavdplas** [UUDigitalHumanitieslab/I-analyzer#936]
For the search filter components, the state of the filter is communicated both to and from the filter through the current `corpus` object,specifically `corpus.fields[x].searchFilter.currentData`.

(This is not universal in the application, the current filter state is usually communicated through the `queryModel`.)

The fact that filter states are so deeply embedded in the corpus definition causes a lot of issues with change detection: for example, when changing `currentData`, a component with the corpus object as input does not run `ngOnChanges`. There is a lot of extra logic with eventemitters and the like to trigger update functions.

The system would probably work better (and be more intelligible) if the filter components were based on the `paramDirective` and communicated the state through the route. (I.e., update filter when the route changes, update route when the user interacts with the filter.) The search component already has functionality in place to update the query model based on filter values in the route.

**Comment by BeritJanssen** [comment]
With #1403 , this issue is obsolete.
